# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://mowenliunian.top
date_format: "ordinal"
title: "莫问流年"
subtitle: "Stay focused and work hard!"
description: "莫问流年的个人博客"
keywords: 莫问流年, mowenliunian
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: mowenliunian
organization: 
organization_url: 
github_username: mowenliunian
location: Beijing, China
email: xuhuifeng1990@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: mzlogin/mzlogin.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: mowenliunian
    repo: blog-comments
    oauth:
        client_id: 0b34cb8fe609a0e3c08a
        client_secret: 366a6c20d8dcf1981f019170f0653bddb57aa445
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: mowenliunian
    repo: blog-comments
    clientID: 0b34cb8fe609a0e3c08a
    clientSecret: 366a6c20d8dcf1981f019170f0653bddb57aa445
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-141364930-1

github: [metadata]

# ---------------- #
#    Switches     #
# ---------------- #
switch:
  sidebar-popular-repo: false

# 可选组件
components:
  # 分享
  # weibo,qq,wechat,douban,qzone,linkedin,facebook,twitter
  share:
    enabled: false
    hide-platforms: tencent,diandian,google,douban,linkedin